#!/usr/bin/env bash
# Быстрый старт с дизайн-токенами MTGAGRO.PRO

echo "=== Дизайн-токены MTGAGRO.PRO установлены ==="
echo ""
echo "📁 Структура:"
echo "  @/shared/config/"
echo "  ├── theme/"
echo "  │   ├── design-tokens.ts    (основные токены)"
echo "  │   ├── types.ts            (TypeScript типы)"
echo "  │   ├── utils.ts            (утилит-функции)"
echo "  │   ├── examples.ts         (примеры использования)"
echo "  │   ├── index.ts            (главный экспорт)"
echo "  │   └── README.md           (документация)"
echo "  ├── MIGRATION_GUIDE.md      (руководство миграции)"
echo "  └── index.ts               (главный экспорт конфига)"
echo ""
echo "🚀 Как начать:"
echo ""
echo "1. В компонентах используйте токены:"
echo "   import { colors, spacing, typography } from '@/shared/config/theme';"
echo ""
echo "2. Применяйте в стилях:"
echo "   backgroundColor: colors.primary[600],"
echo "   padding: spacing[4],"
echo ""
echo "3. Используйте TypeScript типы:"
echo "   import type { ColorKey, FontSize } from '@/shared/config/theme/types';"
echo ""
echo "4. Используйте утилит-функции:"
echo "   import { getColorByPath, getTransition } from '@/shared/config/theme/utils';"
echo ""
echo "📖 Документация:"
echo "  - Полная документация: @/shared/config/theme/README.md"
echo "  - Примеры кода: @/shared/config/theme/examples.ts"
echo "  - Гайд миграции: @/shared/config/MIGRATION_GUIDE.md"
echo ""
echo "🎨 Доступные токены:"
echo "  - colors        (первичные, вторичные, нейтральные, семантические)"
echo "  - typography    (шрифты, размеры, стили)"
echo "  - spacing       (отступы от 4px до 384px)"
echo "  - componentSizes (кнопки, инпуты, аватары)"
echo "  - borderRadius  (от 0px до full)"
echo "  - shadows       (от xs до 2xl)"
echo "  - zIndex        (слои)"
echo "  - breakpoints   (адаптивность)"
echo "  - transitions   (анимации)"
echo ""
echo "💡 Подробнее хотите? Откройте README.md или examples.ts!"
echo ""
