import type { OnboardingSlide } from "./types";

export const onboardingSlides: OnboardingSlide[] = [
  {
    id: 1,
    title: "Заказать просто",
    description: "Сделать заказ теперь можно в три клика",
    imageUrl: "/src/assets/onboarding/1.svg",
    modalHeight: 604,
    modalTop: 173.5,
    contentHeight: 388,
    sliderHeight: 248,
    headingTop: 296,
    headingHeight: 92,
    dotsTop: 268,
  },
  {
    id: 2,
    title: "Выгодно",
    description:
      "Мираторг Pro — это удобно: собрали для вас все промо акции в одном разделе",
    imageUrl: "/src/assets/onboarding/2.svg",
    modalHeight: 616,
    modalTop: 167.5,
    contentHeight: 400,
    sliderHeight: 248,
    headingTop: 296,
    headingHeight: 104,
    dotsTop: 268,
  },
  {
    id: 3,
    title: "Каталог под рукой",
    description:
      "Ожидание = реальность: товары всегда соответствуют фотографиям в каталоге",
    imageUrl: "/src/assets/onboarding/3.svg",
    modalHeight: 627,
    modalTop: 162,
    contentHeight: 411,
    sliderHeight: 259,
    headingTop: 307,
    headingHeight: 104,
    dotsTop: 279,
  },
  {
    id: 4,
    title: "Удобно",
    description:
      "Проверить баланс, заказать счет на оплату и отследить статус поставки можно в личном кабинете",
    imageUrl: "/src/assets/onboarding/4.svg",
    modalHeight: 636,
    modalTop: 157.5,
    contentHeight: 420,
    sliderHeight: 248,
    headingTop: 296,
    headingHeight: 124,
    dotsTop: 268,
  },
  {
    id: 5,
    title: "Всегда на связи",
    description: "Остались вопросы? Наш телеграм-бот поможет",
    imageUrl: "/src/assets/onboarding/5.svg",
    modalHeight: 616,
    modalTop: 167.5,
    contentHeight: 400,
    sliderHeight: 248,
    headingTop: 296,
    headingHeight: 104,
    dotsTop: 268,
  },
];
